# Generated by Django 4.2 on 2023-05-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_blog_author_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='%y/%m/%d'),
        ),
    ]
